In [18]:
import pandas as pd

In [19]:
df=pd.read_csv("spam.csv")

In [20]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [21]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [22]:
# Creating a new column "spam" with binary values:
# 1 for "spam" messages and 0 for "ham" (non-spam) messages
df["spam"]=df["Category"].apply(lambda x: 1 if x=="spam" else 0)

In [23]:
# Checking the shape of the dataset (number of rows and columns)
df.shape

(5572, 3)

In [24]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

Train Test Split


In [25]:
# Importing train_test_split from sklearn for splitting the data into training and testing sets
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.Message,df.spam,test_size=0.2)
# Splitting the dataset into training and testing sets:
# X_train, X_test contain the message text (independent variable)
# y_train, y_test contain the spam labels (dependent variable)

In [26]:
X_train.shape

(4457,)

In [27]:
X_test.shape

(1115,)

In [28]:
#bag of words
# Bag of Words (BOW) model for feature extraction
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()   # Initializing the CountVectorizer to convert text data into numerical feature vectors
X_train_cv=v.fit_transform(X_train.values)   # Fitting and transforming the training data into a sparse matrix
X_train_cv      # Displaying the sparse matrix

<4457x7755 sparse matrix of type '<class 'numpy.int64'>'
	with 59037 stored elements in Compressed Sparse Row format>

In [29]:
# Converting the sparse matrix to an array and displaying the first row
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [30]:
# Converting the entire sparse matrix to a NumPy array for further processing
X_train_np=X_train_cv.toarray()
X_train_np

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [31]:
#Naive Bais Model
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()    # Initializing the Multinomial Naive Bayes classifier
model.fit(X_train_cv,y_train)     # Fitting the model using the training data

MultinomialNB()

In [32]:
# Transforming the test data into the same format as the training data using the fitted vectorizer
X_test_cv=v.transform(X_test)  

Evaluate Performance

In [33]:
# Importing classification_report from sklearn to evaluate the model's performance
from sklearn.metrics import classification_report

y_pred=model.predict(X_test_cv)    # Predicting the labels for the test data
print(classification_report(y_test,y_pred))   # Printing the classification report to evaluate precision, recall, and F1-score


              precision    recall  f1-score   support

           0       0.98      1.00      0.99       963
           1       0.98      0.90      0.94       152

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [34]:
emails=[
    'Hey mohan , can we get together to watch football game tomorrow',
    'upto 20% discount obn parking ,exclusive offer just for you .Dont miss'
]

emails_count=v.transform(emails)  # Transforming the new email messages using the fitted vectorizer
model.predict(emails_count)    # Predicting whether the emails are spam (1) or ham (0)

array([0, 1], dtype=int64)